### ISSUE TITLE
version 1.3.4 is using buggy/non-tagged version of spectrum

### ISSUE THREAD

**Issue by ronen** [cskevint/spectrum-rails#8]
the version of spectrum.js included in spectrum-rails/vendor has the buggy code mentioned in bgrins/spectrum#223 and which apparently isn't actually in the 1.3.4 release.

I switched from spectrum-rails to [rails-assets](https://rails-assets.org)-spectrum v1.3.4 and that doesn't have the buggy code and is working fine.

(I'll just keep going with rails-assets actually, that seems to have obviated the need for handmade gems such as this one.  but thanks for having made it until now!)

**Comment by cskevint** [comment]
I didn't know about rails-assets.org. Thanks for sharing.
